### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by shakirmshaker** [AxeldeRomblay/MLBox#96]
**When I am traying to install, I get this long massage:**

C:\Users\shaki>pip install mlbox
Error processing line 7 of c:\python38\lib\site-packages\pywin32.pth:

  Traceback (most recent call last):
    File "c:\python38\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'pywin32_bootstrap'

Remainder of file ignored
Requirement already satisfied: mlbox in c:\python38\lib\site-packages\mlbox-0.8.2-py3.8.egg (0.8.2)
Collecting numpy==1.17.0
  Using cached numpy-1.17.0.zip (6.5 MB)
Collecting scipy==1.3.0
  Using cached scipy-1.3.0.tar.gz (23.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\shaki\AppData\Local\Temp\tmpctdu0l9c'
         cwd: C:\Users\shaki\AppData\Local\Temp\pip-install-ovjcgxih\scipy
    Complete output (212 lines):
    lapack_opt_info:
    lapack_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['c:\\python38\\lib', 'C:\\', 'c:\\python38\\libs']
      NOT AVAILABLE

    openblas_lapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries openblas not found in ['c:\\python38\\lib', 'C:\\', 'c:\\python38\\libs']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE

    openblas_clapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries openblas,lapack not found in ['c:\\python38\\lib', 'C:\\', 'c:\\python38\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in c:\python38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\python38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in c:\python38\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\python38\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in c:\python38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\python38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in c:\python38\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\python38\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in c:\python38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\python38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in c:\python38\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\python38\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in c:\python38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\python38\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in c:\python38\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\python38\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack not found in ['c:\\python38\\lib', 'C:\\', 'c:\\python38\\libs']
      NOT AVAILABLE

    lapack_src_info:
      NOT AVAILABLE

      NOT AVAILABLE

    Error processing line 7 of c:\python38\lib\site-packages\pywin32.pth:

      Traceback (most recent call last):
        File "c:\python38\lib\site.py", line 169, in addpackage
          exec(line)
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'pywin32_bootstrap'

    Remainder of file ignored
    Error processing line 7 of c:\python38\lib\site-packages\pywin32.pth:

      Traceback (most recent call last):
        File "c:\python38\lib\site.py", line 169, in addpackage
          exec(line)
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'pywin32_bootstrap'

    Remainder of file ignored
    setup.py:111: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp
    setup.py:386: UserWarning: Unrecognized setuptools command ('dist_info --egg-base C:\Users\shaki\AppData\Local\Temp\pip-modern-metadata-qky4rpuh'), proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
    Running from scipy source directory.
    C:\Users\shaki\AppData\Local\Temp\pip-build-env-7stzacuq\overlay\Lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    C:\Users\shaki\AppData\Local\Temp\pip-build-env-7stzacuq\overlay\Lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    C:\Users\shaki\AppData\Local\Temp\pip-build-env-7stzacuq\overlay\Lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    Traceback (most recent call last):
      File "c:\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 257, in <module>
        main()
      File "c:\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "c:\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\shaki\AppData\Local\Temp\pip-build-env-7stzacuq\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\shaki\AppData\Local\Temp\pip-build-env-7stzacuq\overlay\Lib\site-packages\setuptools\build_meta.py", line 249, in run_setup
        super(_BuildMetaLegacyBackend,
      File "C:\Users\shaki\AppData\Local\Temp\pip-build-env-7stzacuq\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 505, in <module>
        setup_package()
      File "setup.py", line 501, in setup_package
        setup(**metadata)
      File "C:\Users\shaki\AppData\Local\Temp\pip-build-env-7stzacuq\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "setup.py", line 403, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
    ----------------------------------------
**ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\shaki\AppData\Local\Temp\tmpctdu0l9c' Check the logs for full command output.**

**Comment by Rubix982** [comment]
Hi @shakirmshaker !
I found a relevant problem at https://stackoverflow.com/questions/58989806/anaconda-terminal-error-pywin32-bootstrap .

Saving you a link, the solution is either this,
`pip install pywin32==225`
or
`pip install --ignore-installed pywin32`

Let me know if it works for you. I can't recreate it, exactly because my machine is on Linux right now. Sorry.

**Comment by AxeldeRomblay** [comment]
Thank you @Rubix982 for the precious help ! @shakirmshaker is it ok for you now ?

**Comment by kaushikk1999** [comment]
**not able to install mlbox in jupyter notebook with pip or cmd**




this error is coming




Collecting mlbox
  Using cached mlbox-0.8.5.tar.gz (31 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting numpy==1.18.2
  Using cached numpy-1.18.2.zip (5.4 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [198 lines of output]
  Running from numpy source directory.
  <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  C:\Users\yokau\AppData\Local\Temp\pip-install-byh7ag91\numpy_3a4201458aa843b2b2e9eb7d25b5d977\tools\cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    required_version = LooseVersion('0.29.14')
  C:\Users\yokau\AppData\Local\Temp\pip-install-byh7ag91\numpy_3a4201458aa843b2b2e9eb7d25b5d977\tools\cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(cython_version) < required_version:
  Processing numpy/random\_bounded_integers.pxd.in
  Processing numpy/random\mtrand.pyx
  Processing numpy/random\_bit_generator.pyx
  Processing numpy/random\_bounded_integers.pyx.in
  Processing numpy/random\_common.pyx
  Processing numpy/random\_generator.pyx
  Processing numpy/random\_mt19937.pyx
  Processing numpy/random\_pcg64.pyx
  Processing numpy/random\_philox.pyx
  Processing numpy/random\_sfc64.pyx
  Cythonizing sources
  blas_opt_info:
  blas_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:\\Users\\yokau\\anaconda3\\lib', 'C:\\', 'C:\\Users\\yokau\\anaconda3\\libs']
    NOT AVAILABLE
  
  blis_info:
    libraries blis not found in ['C:\\Users\\yokau\\anaconda3\\lib', 'C:\\', 'C:\\Users\\yokau\\anaconda3\\libs']
    NOT AVAILABLE
  
  openblas_info:
    libraries openblas not found in ['C:\\Users\\yokau\\anaconda3\\lib', 'C:\\', 'C:\\Users\\yokau\\anaconda3\\libs']
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Could not locate executable DF
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  Could not locate executable flang
  don't know how to compile Fortran code on platform 'nt'
    NOT AVAILABLE
  
  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas not found in ['C:\\Users\\yokau\\anaconda3\\lib', 'C:\\', 'C:\\Users\\yokau\\anaconda3\\libs']
    NOT AVAILABLE
  
  atlas_3_10_blas_info:
    libraries satlas not found in ['C:\\Users\\yokau\\anaconda3\\lib', 'C:\\', 'C:\\Users\\yokau\\anaconda3\\libs']
    NOT AVAILABLE
  
  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\yokau\\anaconda3\\lib', 'C:\\', 'C:\\Users\\yokau\\anaconda3\\libs']
    NOT AVAILABLE
  
  atlas_blas_info:
    libraries f77blas,cblas,atlas not found in ['C:\\Users\\yokau\\anaconda3\\lib', 'C:\\', 'C:\\Users\\yokau\\anaconda3\\libs']
    NOT AVAILABLE
  
  accelerate_info:
    NOT AVAILABLE
  
  C:\Users\yokau\AppData\Local\Temp\pip-install-byh7ag91\numpy_3a4201458aa843b2b2e9eb7d25b5d977\numpy\distutils\system_info.py:1896: UserWarning:
      Optimized (vendor) Blas libraries are not found.
      Falls back to netlib Blas library which has worse performance.
      A better performance should be easily gained by switching
      Blas library.
    if self._calc_info(blas):
  blas_info:
    libraries blas not found in ['C:\\Users\\yokau\\anaconda3\\lib', 'C:\\', 'C:\\Users\\yokau\\anaconda3\\libs']
    NOT AVAILABLE
  
  C:\Users\yokau\AppData\Local\Temp\pip-install-byh7ag91\numpy_3a4201458aa843b2b2e9eb7d25b5d977\numpy\distutils\system_info.py:1896: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    if self._calc_info(blas):
  blas_src_info:
    NOT AVAILABLE
  
  C:\Users\yokau\AppData\Local\Temp\pip-install-byh7ag91\numpy_3a4201458aa843b2b2e9eb7d25b5d977\numpy\distutils\system_info.py:1896: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    if self._calc_info(blas):
    NOT AVAILABLE
  
  non-existing path in 'numpy\\distutils': 'site.cfg'
  lapack_opt_info:
  lapack_mkl_info:
    libraries mkl_rt not found in ['C:\\Users\\yokau\\anaconda3\\lib', 'C:\\', 'C:\\Users\\yokau\\anaconda3\\libs']
    NOT AVAILABLE
  
  openblas_lapack_info:
    libraries openblas not found in ['C:\\Users\\yokau\\anaconda3\\lib', 'C:\\', 'C:\\Users\\yokau\\anaconda3\\libs']
    NOT AVAILABLE
  
  openblas_clapack_info:
    libraries openblas,lapack not found in ['C:\\Users\\yokau\\anaconda3\\lib', 'C:\\', 'C:\\Users\\yokau\\anaconda3\\libs']
    NOT AVAILABLE
  
  flame_info:
    libraries flame not found in ['C:\\Users\\yokau\\anaconda3\\lib', 'C:\\', 'C:\\Users\\yokau\\anaconda3\\libs']
    NOT AVAILABLE
  
  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in C:\Users\yokau\anaconda3\lib
    libraries tatlas,tatlas not found in C:\Users\yokau\anaconda3\lib
    libraries lapack_atlas not found in C:\
    libraries tatlas,tatlas not found in C:\
    libraries lapack_atlas not found in C:\Users\yokau\anaconda3\libs
    libraries tatlas,tatlas not found in C:\Users\yokau\anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE
  
  atlas_3_10_info:
    libraries lapack_atlas not found in C:\Users\yokau\anaconda3\lib
    libraries satlas,satlas not found in C:\Users\yokau\anaconda3\lib
    libraries lapack_atlas not found in C:\
    libraries satlas,satlas not found in C:\
    libraries lapack_atlas not found in C:\Users\yokau\anaconda3\libs
    libraries satlas,satlas not found in C:\Users\yokau\anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE
  
  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in C:\Users\yokau\anaconda3\lib
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\yokau\anaconda3\lib
    libraries lapack_atlas not found in C:\
    libraries ptf77blas,ptcblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\Users\yokau\anaconda3\libs
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\yokau\anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE
  
  atlas_info:
    libraries lapack_atlas not found in C:\Users\yokau\anaconda3\lib
    libraries f77blas,cblas,atlas not found in C:\Users\yokau\anaconda3\lib
    libraries lapack_atlas not found in C:\
    libraries f77blas,cblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\Users\yokau\anaconda3\libs
    libraries f77blas,cblas,atlas not found in C:\Users\yokau\anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE
  
  lapack_info:
    libraries lapack not found in ['C:\\Users\\yokau\\anaconda3\\lib', 'C:\\', 'C:\\Users\\yokau\\anaconda3\\libs']
    NOT AVAILABLE
  
  C:\Users\yokau\AppData\Local\Temp\pip-install-byh7ag91\numpy_3a4201458aa843b2b2e9eb7d25b5d977\numpy\distutils\system_info.py:1730: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
  lapack_src_info:
    NOT AVAILABLE
  
  C:\Users\yokau\AppData\Local\Temp\pip-install-byh7ag91\numpy_3a4201458aa843b2b2e9eb7d25b5d977\numpy\distutils\system_info.py:1730: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
    NOT AVAILABLE
  
  C:\Users\yokau\AppData\Local\Temp\pip-build-env-itcc0gk7\overlay\Lib\site-packages\setuptools\_distutils\dist.py:265: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  running dist_info
  running build_src
  build_src
  building py_modules sources
  creating build
  creating build\src.win-amd64-3.9
  creating build\src.win-amd64-3.9\numpy
  creating build\src.win-amd64-3.9\numpy\distutils
  building library "npymath" sources
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
<img width="1280" alt="2022-11-25" src="https://user-images.githubusercontent.com/102719203/203915341-d81c8c5c-cd05-442d-8600-1a3531788a7b.png">
